### ISSUE TITLE
[PE-D][Tester B] Filter function does not work with multiple filters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-1/tp#150]
The documentation reads I could run this command
![image.png](https://raw.githubusercontent.com/MagnificentCreature/ped/main/files/39ce4a69-286b-490e-b8e4-7a9135b342a1.png)

But I get an error when I try to do it
![image.png](https://raw.githubusercontent.com/MagnificentCreature/ped/main/files/236e9f5a-adb0-4f43-a73d-5a3ceb11afbf.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: MagnificentCreature/ped#4

**Comment by shashahchk** [comment]
UG has been correctly updated to accept one parameter.

**Comment by s-kybound** [comment]
Marked as duplicate of #144
