### ISSUE TITLE
[PE-D][Tester E] Filter command behaviour for sequence of keyword and command is not aligned with UG.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-1/tp#151]
In the UG, it states that the sequence of the command and keywords doesn't matter, which is not shown when i try `Google/c`.

![image.png](https://raw.githubusercontent.com/nubnubyas/ped/main/files/31af7367-7e0c-4835-bf74-d904ac8e290c.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nubnubyas/ped#6

**Comment by shashahchk** [comment]
The UG was vague, now has been fixed to show the exact format.

**Comment by s-kybound** [comment]
Order refers to the keywords, not the order of text. UG updated, but marked as invalid.
