### ISSUE TITLE
[PE-D][Tester A] No possible ways to get out of filtered list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-1/tp#152]
![image.png](https://raw.githubusercontent.com/ChangruHenryQian/ped/main/files/555ed1b1-21cf-4669-abb6-b2db8db4e5f8.png)

The current version does not support a method to return to the original list after filtering. So I am trapped in the filtered list after filtering.

Good ways to improve include adding a `list` feature or fixing the default `filter`.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ChangruHenryQian/ped#4

**Comment by shashahchk** [comment]
The user guide has been correctly updated to show filter default command as the correct way to return to all internship entries list.

**Comment by s-kybound** [comment]
Marked as duplicate of #142
