### ISSUE TITLE
[PE-D][Tester E] Missing image in UG under sort command.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-1/tp#158]
![image.png](https://raw.githubusercontent.com/nubnubyas/ped/main/files/b6b595da-8f03-4c39-932b-2ae7c28f23ff.png)

![image.png](https://raw.githubusercontent.com/nubnubyas/ped/main/files/627ec9b6-9e5a-484a-8310-a2ad8a9ed2df.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: nubnubyas/ped#8

**Comment by s-kybound** [comment]
Marked as duplicate of #138
