### ISSUE TITLE
[PE-D][Tester B] Filter functionality not properly documented

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-1/tp#164]
I did not realise I could filter dates by a range when I was reading the UG.

In order for me to notice this, I had to purposefully input a bad command format for filter
ie "`filter c`"

Then scroll and read through the small cli output box until I found 
the example "`filter du/2-3`".
The text alone which just says "Parameters 2: PREFIX/X-Y"
Does not also explain it quite well what this does.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: MagnificentCreature/ped#5

**Comment by shashahchk** [comment]
The user guide has been correctly updated to show the different filter command formats.

**Comment by s-kybound** [comment]
Marked as duplicate of #139
