### ISSUE TITLE
[PE-D][Tester E] Encounter bug when missing space between category.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-1/tp#166]
A bug was encountered when the following command was inputted `filter c/Jane Streea/`. This can be valid concern if user did not pressed space during typing.
![image.png](https://raw.githubusercontent.com/nubnubyas/ped/main/files/c60fcfe6-3f0d-4337-af8a-9509c1841fa5.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nubnubyas/ped#11

**Comment by shashahchk** [comment]
Not relevant, should only accept one category

**Comment by s-kybound** [comment]
This is relevant as user input into the filter command produced an uncaught exception. Still, marked as duplicate of #141
