### ISSUE TITLE
[PE-D][Tester B] Missing Image for expected output of sort 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-1/tp#172]
![image.png](https://raw.githubusercontent.com/MagnificentCreature/ped/main/files/92ed827d-978f-4187-92a2-2c930d88ef0f.png)

![image.png](https://raw.githubusercontent.com/MagnificentCreature/ped/main/files/6e9f921c-8b30-4469-a377-576af1aecb7a.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: MagnificentCreature/ped#9

**Comment by s-kybound** [comment]
Marked as duplicate of #138
