### ISSUE TITLE
[PE-D][Tester C] filter does not accept multiple parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-1/tp#177]
The example in the UG shows filter being applied on multiple parameters:
![image.png](https://raw.githubusercontent.com/craigtonlian/ped/main/files/e5776389-0c11-4a73-a94e-92b8c617539b.png)

But when the user attempts that, it gets this error that dictates only 1 parameter:
![image.png](https://raw.githubusercontent.com/craigtonlian/ped/main/files/9205d73b-036a-4a39-b86f-fc064ec72a9c.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: craigtonlian/ped#16

**Comment by shashahchk** [comment]
The user guide has been correctly updated to only accept one parameter.

**Comment by s-kybound** [comment]
Marked as duplicate of #144
