### ISSUE TITLE
[PE-D][Tester D] Filter Not Accepting Multiple Parameters

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-1/tp#184]
Although the user guide claims to support multiple parameters for the filter command, the system displays an error that states that the filter command should only accept one parameter when a sample command was entered.

![image.png](https://raw.githubusercontent.com/joeng03/ped/main/files/47fc5669-b496-49ca-90fd-726bacb4d6d5.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: joeng03/ped#1

**Comment by shashahchk** [comment]
The user guide has been correctly updated to only accept one parameter.

**Comment by s-kybound** [comment]
Marked as duplicate of #144
