### ISSUE TITLE
[PE-D][Tester D] Typo in Error Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-1/tp#185]
There is a typo in the error message given by the system, where 'earlier' and 'than' are not seperated by a space.

![Screenshot 2023-11-03 224710.png](https://raw.githubusercontent.com/joeng03/ped/main/files/ebaa3497-b874-4df0-8faf-3d9e1e220f03.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: joeng03/ped#2

**Comment by jinyang628** [comment]
No issue on the create command side. Double check whether modify command has this issue. I cant seem to check for u because i cant modify an internship's deadline

**Comment by s-kybound** [comment]
Marked as duplicate of #159
