### ISSUE TITLE
Devise a way to jump back to original location after navigating in UG

### ISSUE THREAD

**Issue by jinyang628** [AY2324S1-CS2103T-W17-1/tp#194]
Suppose I click on Command Summary link,

![image](https://github.com/AY2324S1-CS2103T-W17-1/tp/assets/81862152/e9e40f1e-2c0a-49c5-b13b-9bf93b07d99a)

I arrive to the bottom of the page.

![image](https://github.com/AY2324S1-CS2103T-W17-1/tp/assets/81862152/621a30e6-f691-4032-b2ef-a4ac0f659401)

Is there a way to do some sort of "return to original location button" so users dont have to scroll all the way back up. This problem is mentioned by a few testers (and ms amy too) and i spent quite some time trying to figure how to do it (didnt manage to). Can you find a way to do it?

You cannot rely on the Table of Content to the RIGHT of the UG as shown on the website. This is because it will not be in the final PDF when we do print + save as pdf. This must be some sort of button within the actual UG

**Comment by yongning0310** [comment]
It seems like there's no way of dynamically generating a link that will bring you back to the 'original location' based on the page you came from. I have two suggestions for this problem:

1. Move the Command Summary closer to the top if we think that users will want to refer to this section frequently, and at the same time, would like to go back to the top after taking a quick glance.

2. Hardcode a link or button on every page to bring the user to the Table of Contents.

@jinyang628

**Comment by s-kybound** [comment]
Resolved because of @yongning0310 . Thank you!
